name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to EC2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --launch-template LaunchTemplateName=demo-task-manager-template \
            --query 'Instances[0].InstanceId' \
            --output text)
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          OLD_INSTANCES=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=demo-task-manager-dev" \
            "Name=instance-id,Values!=$INSTANCE_ID" \
            --query 'Reservations[].Instances[].InstanceId' \
            --output text)
          if [ ! -z "$OLD_INSTANCES" ]; then
            aws ec2 terminate-instances --instance-ids $OLD_INSTANCES
          fi
